/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.1.3-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import io.swagger.annotations.*;
import org.springframework.core.io.Resource;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.context.request.NativeWebRequest;

import javax.validation.constraints.*;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-10-03T13:53:56.637+02:00[Europe/Oslo]")

@Validated
@Api(value = "report", description = "the report API")
public interface ReportApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    @ApiOperation(value = "Returns the report in the JSON format.", nickname = "reportGet", notes = "", response = Resource.class, tags={  })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "A JSON file.", response = Resource.class) })
    @RequestMapping(value = "/report",
        produces = { "application/json" },
        method = RequestMethod.GET)
    default ResponseEntity<Resource> reportGet() {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
