/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.9-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package dk.kb.picture.api;

import dk.kb.picture.model.PictureMetadata;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-09-25T11:58:48.758+02:00")

@Api(value = "findPictureMetadata", description = "the findPictureMetadata API")
public interface FindPictureMetadataApi {

    @ApiOperation(value = "Find metadata by ID", nickname = "getPictureMetadata", notes = "Returns a single picture metadata", response = PictureMetadata.class, tags={ "picture", })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "successful operation", response = PictureMetadata.class),
        @ApiResponse(code = 400, message = "Invalid Picture ID supplied"),
        @ApiResponse(code = 404, message = "Picture not found") })
    @RequestMapping(value = "/findPictureMetadata/{pictureId}",
        produces = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<PictureMetadata> getPictureMetadata(@ApiParam(value = "ID of Picture to return",required=true) @PathVariable("pictureId") Long pictureId);

}
