swagger: '2.0' #version of Swagger
info: # High Level information of API
  description: Sample Swagger Demo #Give the description of API
  version: 1.0.0 #API version
  title: Swagger Cumulus Demo # API title
  license: #Swagger license info
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: localhost # Host Name
basePath: /v1 #Basepath when there are multiple versions of API running
tags: # Tag information for each API operation. Multiple tags for multiple API operation
  - name: cumulus_metadata #Tag name
    description: Everything about your picture #Tag description of API operation
schemes:
  - http #security schemes
paths:
  '/findPictureMetadata/{pictureId}': #Request Mapping path of REST API
    get: #Request method type, GET,POST etc.
      tags: # Refer to created tag above
        - picture
      summary: Find metadata by ID #Summary
      description: Returns a single picture metadata #Description of API operation
      operationId: getPictureMetadata #Method name
      produces:
        - application/json #Response content type
      parameters:
        - name: pictureId #Input parameter
          in: path #path variable
          description: ID of Picture to return #description of parameter
          required: true #Is mandatory
          type: integer #data type
          format: int64 #data type format, signed 64 bits
      responses: # API response
        '200': #Successful status code
          description: successful operation #Successful status description
          schema:
            $ref: '#/definitions/PictureMetadata' #Response object details
        '400': #Unsuccessful response code
          description: Invalid Picture ID supplied #Unsuccessful response description
        '404': #Unsuccessful response code
          description: Picture not found #Unsuccessful response description
definitions: # Object definition
  PictureMetadata: #Picture Object
    type: object
    properties: #Object properties
      id: #Id attribute
        type: integer
        format: int64
      firstName: #Firstname attribute
        type: string
        description: Picture First Name #data type description
      lastName: #Lastname attribute
        type: string #Data type
        description: Picture Last Name #Data type description
    xml:
      name: pictureMetadata #xml root element when returning xml
